// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHAXzRvza7S4ANJM25Qx8Eo2wP0kVH-WQ',
    appId: '1:197849697061:web:e124926efa8c74157fe8cc',
    messagingSenderId: '197849697061',
    projectId: 'wasalny-app-cbe2e',
    authDomain: 'wasalny-app-cbe2e.firebaseapp.com',
    storageBucket: 'wasalny-app-cbe2e.appspot.com',
    measurementId: 'G-D2P84QYBL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5YZPgzlpBoWilMweBgjf5NsO9NK303e4',
    appId: '1:197849697061:android:1514b55418c1d6d47fe8cc',
    messagingSenderId: '197849697061',
    projectId: 'wasalny-app-cbe2e',
    storageBucket: 'wasalny-app-cbe2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIBH_Cx2sper4ZTnZgGgxFJOc1OJJT2J0',
    appId: '1:197849697061:ios:5d35a29570379cad7fe8cc',
    messagingSenderId: '197849697061',
    projectId: 'wasalny-app-cbe2e',
    storageBucket: 'wasalny-app-cbe2e.appspot.com',
    iosBundleId: 'com.example.wasallny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIBH_Cx2sper4ZTnZgGgxFJOc1OJJT2J0',
    appId: '1:197849697061:ios:bb1d98dd290670167fe8cc',
    messagingSenderId: '197849697061',
    projectId: 'wasalny-app-cbe2e',
    storageBucket: 'wasalny-app-cbe2e.appspot.com',
    iosBundleId: 'com.example.wasallny.RunnerTests',
  );
}
